-- Crear tablas
CREATE TABLE IF NOT EXISTS camiones (
  id TEXT PRIMARY KEY,
  nombre TEXT NOT NULL,
  fecha TEXT NOT NULL,
  estado TEXT NOT NULL DEFAULT 'abierto',
  productos JSONB NOT NULL DEFAULT '[]'::jsonb,
  created_at TEXT,
  closed_at TEXT
);

CREATE TABLE IF NOT EXISTS productos (
  id TEXT PRIMARY KEY,
  nombre TEXT NOT NULL,
  emoji TEXT DEFAULT '',
  unidad TEXT DEFAULT 'unidad',
  activo BOOLEAN DEFAULT true,
  precio_default NUMERIC DEFAULT 0,
  nombre_variantes JSONB DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS clientes (
  id TEXT PRIMARY KEY,
  nombre TEXT NOT NULL,
  telefono TEXT DEFAULT ''
);

CREATE TABLE IF NOT EXISTS pedidos (
  id TEXT PRIMARY KEY,
  camion_id TEXT REFERENCES camiones(id),
  cliente_id TEXT REFERENCES clientes(id),
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  estado TEXT NOT NULL DEFAULT 'pendiente',
  created_at TEXT,
  updated_at TEXT
);

-- Insertar productos
INSERT INTO productos (id, nombre, emoji, unidad, activo, precio_default, nombre_variantes) VALUES
('p001', 'Acelga', '🥬', 'manojo', true, 0, '["acelga","aselga"]'),
('p002', 'Achicoria', '🥬', 'unidad', true, 0, '["achicoria","achicioria"]'),
('p003', 'Apio Ensalada', '🥬', 'manojo', true, 0, '["apio ensalada","apio","apelio"]'),
('p004', 'Alcachofa', '🌿', 'unidad', true, 0, '["alcachofa","alcahofa"]'),
('p005', 'Arándano', '🫐', 'bandeja', true, 0, '["arandano","arándano","arandanos"]'),
('p006', 'Arvejas', '🟢', 'kg', true, 0, '["arvejas","arveja","arvea"]'),
('p007', 'Ajos', '🧄', 'kg', true, 0, '["ajos","ajo"]'),
('p008', 'Ají', '🌶️', 'kg', true, 0, '["aji","ají","aji picante"]'),
('p009', 'Aceitunas', '🫒', 'kg', true, 0, '["aceitunas","aceituna"]'),
('p010', 'Beterraga (pqte.)', '🟣', 'paquete', true, 0, '["beterraga","betarraga","remolacha"]'),
('p011', 'Berenjenas', '🍆', 'kg', true, 0, '["berenjenas","berenjena","berengena"]'),
('p012', 'Brusela 800 grs', '🟢', 'bandeja', true, 0, '["brusela","brucela","brócoli","broculi"]'),
('p013', 'Brócoli', '🥦', 'unidad', true, 0, '["brocoli","brócoli"]'),
('p014', 'Coliflor', '⚪', 'unidad', true, 0, '["coliflor","coliflor"]'),
('p015', 'Cebolla Morada', '🧅', 'kg', true, 0, '["cebolla morada","cebolla mor"]'),
('p016', 'Cebolla', '🧅', 'kg', true, 0, '["cebolla","cebolla blanca"]'),
('p017', 'Cebollín', '🌿', 'manojo', true, 0, '["cebollin","cebollín","cebolleta"]'),
('p018', 'Ciboullette', '🌿', 'manojo', true, 0, '["ciboullette","ciboulette"]'),
('p019', 'Choclo Americano', '🌽', 'unidad', true, 0, '["choclo americano","choclo americ","choclo"]'),
('p020', 'Choclo Chileno', '🌽', 'unidad', true, 0, '["choclo chileno","choclo chil"]'),
('p021', 'Ciruelas', '🟣', 'kg', true, 0, '["ciruelas","ciruela","cirelas"]'),
('p022', 'Chirimoyas', '🥑', 'kg', true, 0, '["chirimoyas","chirimoya","chirimollo"]'),
('p023', 'Duraznos', '🍑', 'kg', true, 0, '["duraznos","durazno","durano"]'),
('p024', 'Damascos', '🟠', 'kg', true, 0, '["damascos","damasco","damasgo"]'),
('p025', 'Fresas', '🍓', 'bandeja', true, 0, '["fresas","fresa","frutillas"]'),
('p026', 'Espárragos', '🌿', 'manojo', true, 0, '["esparagos","espárragos","esparago"]'),
('p027', 'Espinaca (pqte.)', '🥬', 'paquete', true, 0, '["espinaca","espinaca paquete","espinca"]'),
('p028', 'Habas', '🟢', 'kg', true, 0, '["habas","haba","avas"]'),
('p029', 'Kiwi', '🥝', 'kg', true, 0, '["kiwi","kiwis","kiiwi"]'),
('p030', 'Limones', '🍋', 'kg', true, 0, '["limones","limon","limón"]'),
('p031', 'Lechuga Larga', '🥬', 'unidad', true, 0, '["lechuga larga","lechuga lg"]'),
('p032', 'Escarolas', '🥬', 'unidad', true, 0, '["escarolas","escarola","escarola"]'),
('p033', 'Lechuga Pastel', '🥗', 'unidad', true, 0, '["lechuga pastel","lechuga pst"]'),
('p034', 'Otra Variedad', '❓', 'unidad', true, 0, '["otra variedad","otra"]'),
('p035', 'Melón Tuna', '🍈', 'unidad', true, 0, '["melon tuna","melón tuna","melon"]'),
('p036', 'Melón Calameño', '🍈', 'unidad', true, 0, '["melon calameño","melón calameño","calameño"]'),
('p037', 'Morrón Verde', '🫑', 'kg', true, 0, '["morron verde","morón verde","morron"]'),
('p038', 'Morrón Rojo', '🫑', 'kg', true, 0, '["morron rojo","morón rojo"]'),
('p039', 'Morrón Amarillo', '🫑', 'kg', true, 0, '["morron amarillo","morón amarillo","amarillo"]'),
('p040', 'Mango (kg)', '🥭', 'kg', true, 0, '["mango","mango kg"]'),
('p041', 'Membrillo', '🍎', 'kg', true, 0, '["membrillo","membrigo"]'),
('p042', 'Manzana Verde', '🍏', 'kg', true, 0, '["manzana verde","manzana vde"]'),
('p043', 'Manzanas Rojas', '🍎', 'kg', true, 0, '["manzanas rojas","manzana roja","manzana rojas"]'),
('p044', 'Naranjas', '🍊', 'kg', true, 0, '["naranjas","naranja"]'),
('p045', 'Mandarinas', '🍊', 'kg', true, 0, '["mandarinas","mandarina","mandarina"]'),
('p046', 'Níspero', '🟡', 'kg', true, 0, '["nispero","níspero","niespero"]'),
('p047', 'Pomelo', '🍊', 'kg', true, 0, '["pomelo","pomelos"]'),
('p048', 'Papas', '🥔', 'kg', true, 0, '["papas","papa","pasas"]'),
('p049', 'Puerro (pqte.)', '🌿', 'paquete', true, 0, '["puerro paquete","puerro","puero"]'),
('p050', 'Pepino Fruta', '🥒', 'kg', true, 0, '["pepino fruta","pepino fta"]'),
('p051', 'Pepino Ensalada', '🥒', 'kg', true, 0, '["pepino ensalada","pepino ens"]'),
('p052', 'Plátanos', '🍌', 'kg', true, 0, '["platanos","platano","banana"]'),
('p053', 'Paltas', '🥑', 'kg', true, 0, '["paltas","palta","aguacate"]'),
('p054', 'Peras', '🍐', 'kg', true, 0, '["peras","pera","pers"]'),
('p055', 'Piñas', '🍍', 'unidad', true, 0, '["piñas","piña","pinas"]'),
('p056', 'Poroto Verde', '🫘', 'kg', true, 0, '["poroto verde","poroto vde"]'),
('p057', 'Granados', '🔴', 'kg', true, 0, '["granados","granado","granadas"]'),
('p058', 'Repollo', '🥬', 'unidad', true, 0, '["repollo","replo"]'),
('p059', 'Rábanos', '🔴', 'manojo', true, 0, '["rabanos","rábanos","ravano"]'),
('p060', 'Sandías', '🍉', 'kg', true, 0, '["sandias","sandia","sandias"]'),
('p061', 'Tomates', '🍅', 'kg', true, 0, '["tomates","tomate"]'),
('p062', 'Tomate Cherry', '🍅', 'bandeja', true, 0, '["tomate cherry","cherry"]'),
('p063', 'Tunas', '🌵', 'unidad', true, 0, '["tunas","tuna"]'),
('p064', 'Zapallo Italiano', '🎃', 'kg', true, 0, '["zapallo italiano","zapallo ita"]'),
('p065', 'Zapallo Trozo', '🎃', 'kg', true, 0, '["zapallo trozo","zapallo","sapallo"]'),
('p066', 'Zanahorias', '🥕', 'kg', true, 0, '["zanahorias","zanahoria","zanaoria","znahoria"]'),
('p067', 'Uvas S/P Blancas', '🍇', 'kg', true, 0, '["uvas s/p blancas","uvas blancas","uvas bl"]'),
('p068', 'Uvas Negras', '🍇', 'kg', true, 0, '["uvas negras","uvas ng"]'),
('p069', 'Granadas', '🔴', 'kg', true, 0, '["granadas","granada","granados"]'),
('p070', 'Mancaquí', '🟠', 'kg', true, 0, '["mancaqui","mancaquí","mancaki"]'),
('p071', 'Caquí', '🟠', 'kg', true, 0, '["caqui","caquí","caki"]'),
('p072', 'Condimentos', '🌿', 'unidad', true, 0, '["condimentos","condimento"]'),
('p073', 'Champiñón (bandeja)', '🍄', 'bandeja', true, 0, '["champiñones","championes","champinones","champignon"]'),
('p074', 'Castañas', '🌰', 'kg', true, 0, '["castanas","castañas","castana"]'),
('p075', 'Piñones', '🌰', 'kg', true, 0, '["pinones","piñones","pinon"]'),
('p076', 'Lentejas', '🫘', 'kg', true, 0, '["lentejas","lenteja"]'),
('p077', 'Porotos Tort.', '🟢', 'kg', true, 0, '["porotos tortuga","porotos tort","porotos"]'),
('p078', 'Miel', '🍯', 'unidad', true, 0, '["miel"]'),
('p079', 'Nueces', '🥜', 'kg', true, 0, '["nueces","nuez"]'),
('p080', 'Almendras', '🥜', 'kg', true, 0, '["almendras","almendra"]'),
('p081', 'Mix Frutos Secos', '🥜', 'kg', true, 0, '["mix frutos secos","mix secos","mix"]'),
('p082', 'Huevos (30 unid)', '🥚', 'bandeja', true, 0, '["huevos 30","huevos","uevos"]'),
('p083', 'Harina 5 kg', '🌾', 'bolsa', true, 0, '["harina 5 kg","harina","arina"]'),
('p084', 'Cilantro', '🌿', 'manojo', true, 0, '["cilantro","corilantro","silantro"]'),
('p085', 'Perejil', '🌿', 'manojo', true, 0, '["perejil","peregil"]'),
('p086', 'Apio Sopa', '🥬', 'manojo', true, 0, '["apio sopa","apio s"]'),
('p087', 'Tomillo', '🌿', 'manojo', true, 0, '["tomillo","tomilo"]'),
('p088', 'Surtido Verduras', '🥗', 'bolsa', true, 0, '["surtido verduras","surtido","suritido"]'),
('p089', 'Albahaca', '🌿', 'manojo', true, 0, '["albahaca","albajaca"]')
ON CONFLICT (id) DO UPDATE SET
  nombre = EXCLUDED.nombre,
  emoji = EXCLUDED.emoji,
  unidad = EXCLUDED.unidad,
  activo = EXCLUDED.activo,
  nombre_variantes = EXCLUDED.nombre_variantes;